-- liquibase formatted sql

-- Changeset fred:create course table

CREATE TABLE course (
                        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        courseTitle VARCHAR(255),
                        platform VARCHAR(255),
                        link TEXT,
                        description TEXT,
                        duration VARCHAR(50)
);