
FROM maven:3.9.6-eclipse-temurin-21-alpine AS builder

WORKDIR /app

COPY pom.xml .
RUN mvn -B dependency:resolve dependency:resolve-plugins

COPY src src

RUN mvn -B clean package -DskipTests

FROM openjdk:21-jdk


WORKDIR /app


COPY --from=builder /app/target/rejob-0.0.1-SNAPSHOT.jar /app/

EXPOSE 8080


CMD ["java", "-jar", "rejob-0.0.1-SNAPSHOT.jar"]
